### ISSUE TITLE
Fortune VIII turns to fortune III when trying to add it to pickaxe

### ISSUE THREAD

**Issue by AdnanuReeves** [xElementzx/EnchantingBooks#1]
Like title says, when I try to add the enchantment from the book it goes to fortune 3..
https://gyazo.com/a8074ad471432aecf1818821c63bf59a

**Comment by xElementzx** [comment]
Hey Mate,

What mod are you using for adding extra levels of enchants

**Comment by xElementzx** [comment]
No response for 18 days. if you get back to me with the mod create a new issue.
